const PARTNER_STATUS = {
  ACTIVE: 'ACTIVE',
  TERMINATED: 'TERMINATED',
  UNAVAILABLE: 'UNAVAILABLE'
} as const

const PARTNER_PERMISSIONS = {
  WRITE: 'WRITE',
  READ: 'READ',
  BALANCE_INQUIRY: 'BALANCE_INQUIRY'
} as const

export { PARTNER_STATUS, PARTNER_PERMISSIONS }
