const TRANSACTION_STATUS = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  VOIDED: 'VOIDED'
} as const

const TRANSACTION_TYPE = {
  PAYMENT: 'PAYMENT',
  REFUND: 'REFUND',
  INTERNAL: 'INTERNAL'
} as const

export { TRANSACTION_STATUS, TRANSACTION_TYPE }
